### ISSUE TITLE
Can't Import any component from Electron

### ISSUE THREAD

**Issue by ekottifiok** [oliverschwendener/electron-fluent-ui#7]
When I `import { desktopCapturer } from "electron";`
and use it like this:
`desktopCapturer.getSources({ types: ['window', 'screen'] })`
`Uncaught ReferenceError: __dirname is not defined`

**Comment by ekottifiok** [comment]
Renderer

**Comment by ekottifiok** [comment]
Does it work on the main? Would try

**Comment by oliverschwendener** [comment]
If you want to do this in the renderer you have to enable the node integration for the browser window. This is not recommended for security reasons but if you want to try it out, set `nodeIntegration: true` when creating the browser window:

packages/main/src/index.ts

```typescript
const createBrowserWindow = (): BrowserWindow => {
    return new BrowserWindow({
        autoHideMenuBar: true,
        webPreferences: {
            nodeIntegration: true,
            preload: join(__dirname, "..", "..", "preload", "dist", "index.cjs"),
        },
    });
};
```

**Comment by ekottifiok** [comment]
it's an electron error
this is the error screenshot [https://drive.google.com/file/d/1IxB-evwY3Fn9RWeq8bFKdJxm5sCxvnlF/view?usp=share_link](url)

**Comment by ekottifiok** [comment]
okay thanks for your speedy reply to the issue
